### ISSUE TITLE
Consider moving `nextTick` into `promise` package

### ISSUE THREAD

**Issue by darscan** [CC-Archived/promise-as3#17]
I realize that the `util` package makes sense when viewed from a "CodeCatalyst" organization perspective, but as a user of this 3rd-party lib it looks a little out of place.

**Comment by ThomasBurleson** [comment]
The nextTick function does seem orphaned. In my mind, however, we have only two solutions: place such methods in a generic utils class or move it into the `promise` package and also replicate it in the FlexExtensions utils lib. 

While it makes sense to move (instead of replicate) nextTick() to the FlexExtensions library, then the Promise-AS3 lib would have an unwanted dependency. 

I also think a `utils` package is a great place to put global and static functions... as both do not necessitate `new` construction.  So, IMHO, the `utils` package is a reasonable compromise that achieves multiple purposes.

**Comment by darscan** [comment]
OK cool, sounds reasonable.
