### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by darscan** [CC-Archived/promise-as3#7]
What is the rationale for all the code living in the `develop` branch when the master branch is pretty much empty?

**Comment by johnyanarella** [comment]
It is not yet officially 'released', still in development and will be undergoing some significant API changes yet.

My original implementation (which can still be found in the `flex-extensions` project) was inspired by jQuery -- I was out to make an AS3 and Flex flavored implementation, rather than a clone of jQuery's implementation. Thomas Burleson ported over some of the newer features added to jQuery's Deferreds, including the Callbacks class. Since then, both he and I have been doing more work involving other JavaScript Deferred/Promise implementations, such as `q` and the customized version of `q` included in `AngularJS`.  In that process, we have became aware of the Promise/A CommonJS spec and realized how significantly jQuery's implementation deviates from the 'standard.'

The current roadmap is to revisit this implementation to make it adhere to the Promise/A spec.  It may also be possible to expose an additional optional facade that matches the jQuery syntax and behavior, but I have not yet fully investigated this possibility.  Additionally, I intend to streamline the API by which common AS3 and Flex asynchronous operations are wrapped as Promises.

Once the API has solidified, the project will be officially released.  Right now, we're intentionally under the radar.

**Comment by darscan** [comment]
Aha! I was investigating doing a port of `Q` when I came across this repo (which I was very happy to find).
